version: '3'
services:
  api:
    container_name: api_semantix
    image: semantix
    build:
      context: app
    ports:
      - 4000:8888
    networks:
      - semantix
  
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: jenkins_home/pipeline
    volumes: 
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - semantix

networks:
  semantix:
  